# Generated by Django 3.2.12 on 2022-05-03 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.AddField(
            model_name='badge',
            name='goal',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='badge',
            name='instruction',
            field=models.CharField(default='Do something cool', max_length=80),
        ),
        migrations.AddField(
            model_name='badge',
            name='title',
            field=models.CharField(default='Cool Badge 123', max_length=40),
        ),
        migrations.AddField(
            model_name='badge',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='badge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='receivedOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(through='gamification.BadgeStatus', to='gamification.Badge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
