# Generated by Django 3.2.12 on 2022-08-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_chatmessage_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='hoverOverText',
            new_name='tooltip',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_balance',
            new_name='currentBalance',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='iconpath',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='iconpath',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='value',
        ),
        migrations.AddField(
            model_name='challengestatus',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statistic',
            name='unit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='statisticsstatus',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annotationStreak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalEnergyCollected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengestatus',
            name='id',
            field=models.CharField(default='0-0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='itemName',
            field=models.CharField(default='Item X', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
