# Generated by Django 3.2.12 on 2022-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_auto_20220503_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='goalunit',
            field=models.CharField(default='images', max_length=20),
        ),
    ]
