# Generated by Django 3.2.12 on 2022-05-11 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_badge_goalunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgestatus',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AlterField(
            model_name='badgestatus',
            name='receivedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
