# Generated by Django 3.2.12 on 2022-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20220811_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='id',
            field=models.CharField(default='0-0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='tooltip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
