# Generated by Django 3.2.12 on 2022-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20220812_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energizerdata',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
