# Generated by Django 3.2.12 on 2022-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20220511_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=80)),
                ('progress', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('challengeType', models.CharField(max_length=80)),
            ],
        ),
    ]
