# Generated by Django 3.2.12 on 2022-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_energizerdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energizerdata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
