# Generated by Django 3.2.12 on 2022-06-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergizerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentEnergy', models.IntegerField(default=0)),
                ('energizersDone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='Item', max_length=40)),
                ('price', models.IntegerField(default=100)),
                ('iconpath', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('value', models.CharField(default='', max_length=40)),
                ('hoverOverText', models.CharField(default='', max_length=40)),
                ('iconpath', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengeType',
            field=models.CharField(default='Daily', max_length=80),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='instruction',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='reward',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='StatisticsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.statistic')),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.shopitem')),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.challenge')),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenges',
            field=models.ManyToManyField(through='gamification.ChallengeStatus', to='gamification.Challenge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items',
            field=models.ManyToManyField(through='gamification.ItemStatus', to='gamification.ShopItem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statistics',
            field=models.ManyToManyField(through='gamification.StatisticsStatus', to='gamification.Statistic'),
        ),
    ]
