# Generated by Django 3.2.12 on 2022-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_auto_20220622_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgestatus',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
