# Generated by Django 3.2.12 on 2022-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_energizerdata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='annotationStreak',
            new_name='annotation_streak_current',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='energizersDone',
            new_name='energizers_completed',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='currentEnergy',
            new_name='energy_current',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='totalEnergyCollected',
            new_name='energy_total',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annotation_coins_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annotation_coins_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annotation_streak_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges_obtained_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_messages_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='energy_expired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images_annotated_night',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images_annotated_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items_bought_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snake_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tags_set_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tetris_played',
            field=models.IntegerField(default=0),
        ),
    ]
