# Generated by Django 3.2.12 on 2022-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20220818_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annotation_time_total',
            field=models.IntegerField(default=0),
        ),
    ]
