# Generated by Django 3.2.12 on 2022-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_badgestatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgestatus',
            name='id',
            field=models.CharField(default='0-0', max_length=8, primary_key=True, serialize=False),
        ),
    ]
