# Generated by Django 3.2.12 on 2022-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_userprofile_annotation_time_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selectedStatistics',
            field=models.CharField(default='', max_length=255),
        ),
    ]
