# Generated by Django 3.2.12 on 2022-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_auto_20220922_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_border',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_background',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_border',
            field=models.CharField(default='', max_length=64),
        ),
    ]
