# Generated by Django 3.2.12 on 2022-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_auto_20220923_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsstatus',
            name='statistic',
        ),
        migrations.RemoveField(
            model_name='statisticsstatus',
            name='userProfile',
        ),
        migrations.RenameField(
            model_name='badgestatus',
            old_name='userProfile',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='challengestatus',
            old_name='userProfile',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='badgestatus',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgestatus',
            name='got',
        ),
        migrations.RemoveField(
            model_name='badgestatus',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='challengestatus',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='items',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='statistics',
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='badgeId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badgestatus',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='challengestatus',
            name='challengeId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengestatus',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengestatus',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annotation_streak_saver',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItemStatus',
        ),
        migrations.DeleteModel(
            name='StatisticsStatus',
        ),
    ]
