# Generated by Django 3.2.12 on 2022-10-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0013_auto_20221006_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgestatus',
            old_name='title',
            new_name='tier',
        ),
        migrations.AlterField(
            model_name='badgestatus',
            name='receivedOn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_class',
            field=models.IntegerField(default=0),
        ),
    ]
