# Generated by Django 3.2.12 on 2022-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0014_auto_20221007_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgestatus',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
