# Generated by Django 3.2.12 on 2022-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0015_alter_badgestatus_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='senderId',
            field=models.IntegerField(default=0),
        ),
    ]
