# Generated by Django 3.2.12 on 2022-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0016_chatmessage_senderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_login',
            new_name='last_login_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ms',
            field=models.IntegerField(default=0),
        ),
    ]
