# Generated by Django 3.2.12 on 2022-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0017_auto_20221008_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='online_status',
            field=models.IntegerField(default=0),
        ),
    ]
