# Generated by Django 3.2.12 on 2023-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0018_alter_userprofile_online_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamifLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selectedBadges',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
