# Generated by Django 3.2.12 on 2023-02-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0019_auto_20230123_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moneyBadgeTier',
            field=models.IntegerField(default=0),
        ),
    ]
