# Generated by Django 3.2.12 on 2023-02-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0020_userprofile_moneybadgetier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamiflog',
            name='event',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
