# Generated by Django 3.2.12 on 2023-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0021_alter_gamiflog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengestatus',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
