# Generated by Django 3.2.12 on 2023-04-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0022_challengestatus_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selectedStatistics',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='ImageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobUrl', models.CharField(default='', max_length=64)),
                ('imageIds', models.JSONField(null=True)),
                ('userProfile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamification.userprofile')),
            ],
        ),
    ]
