# Generated by Django 3.2.12 on 2023-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0023_auto_20230420_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagestatus',
            old_name='jobUrl',
            new_name='jobId',
        ),
        migrations.RenameField(
            model_name='imagestatus',
            old_name='userProfile',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='imagestatus',
            name='id',
            field=models.CharField(default='0-0', max_length=16, primary_key=True, serialize=False),
        ),
    ]
