// Copyright (C) 2020-2022 Intel Corporation
//
// SPDX-License-Identifier: MIT

import React from 'react';
import Icon from '@ant-design/icons';

import SVGCVATLogo from './assets/cvat-logo.svg';
import SVGEmptyTasksIcon from './assets/empty-tasks-icon.svg';
import SVGCursorIcon from './assets/cursor-icon.svg';
import SVGMoveIcon from './assets/move-icon.svg';
import SVGRotateIcon from './assets/rotate-icon.svg';
import SVGFitIcon from './assets/fit-to-window-icon.svg';
import SVGZoomIcon from './assets/zoom-icon.svg';
import SVGRectangleIcon from './assets/rectangle-icon.svg';
import SVGPolygonIcon from './assets/polygon-icon.svg';
import SVGPointIcon from './assets/point-icon.svg';
import SVGEllipseIcon from './assets/ellipse-icon.svg';
import SVGPolylineIcon from './assets/polyline-icon.svg';
import SVGTagIcon from './assets/tag-icon.svg';
import SVGMergeIcon from './assets/merge-icon.svg';
import SVGGroupIcon from './assets/group-icon.svg';
import SVGSplitIcon from './assets/split-icon.svg';
import SVGMainMenuIcon from './assets/main-menu-icon.svg';
import SVGSaveIcon from './assets/save-icon.svg';
import SVGUndoIcon from './assets/undo-icon.svg';
import SVGRedoIcon from './assets/redo-icon.svg';
import SVGFirstIcon from './assets/first-icon.svg';
import SVGBackJumpIcon from './assets/back-jump-icon.svg';
import SVGPreviousIcon from './assets/previous-icon.svg';
import SVGPreviousFilteredIcon from './assets/previous-filtered-icon.svg';
import SVGPreviousEmptyIcon from './assets/previous-empty-icon.svg';
import SVGPlayIcon from './assets/play-icon.svg';
import SVGPauseIcon from './assets/pause-icon.svg';
import SVGNextIcon from './assets/next-icon.svg';
import SVGNextFilteredIcon from './assets/next-filtered-icon.svg';
import SVGNextEmptyIcon from './assets/next-empty-icon.svg';
import SVGForwardJumpIcon from './assets/forward-jump-icon.svg';
import SVGLastIcon from './assets/last-icon.svg';
import SVGInfoIcon from './assets/info-icon.svg';
import SVGFullscreenIcon from './assets/fullscreen-icon.svg';
import SVGObjectOutsideIcon from './assets/object-outside-icon.svg';
import SVGBackgroundIcon from './assets/background-icon.svg';
import SVGForegroundIcon from './assets/foreground-icon.svg';
import SVGCubeIcon from './assets/cube-icon.svg';
import SVGResetPerspectiveIcon from './assets/reset-perspective.svg';
import SVGColorizeIcon from './assets/colorize-icon.svg';
import SVGAITools from './assets/ai-tools-icon.svg';
import SVGBrain from './assets/brain.svg';
import SVGOpenCV from './assets/opencv.svg';
import SVGFilterIcon from './assets/object-filter-icon.svg';
import SVGCVATAzureProvider from './assets/vscode-icons_file-type-azure.svg';
import SVGCVATS3Provider from './assets/S3.svg';
import SVGCVATGoogleCloudProvider from './assets/google-cloud.svg';
import SVGOpenVINO from './assets/openvino.svg';
// gamification stuff
import SVGBadge from './assets/badge-icon.svg';
import SVGBadgeGrey from './assets/badge-grey-icon.svg';
import SVGAnnotationCoin from './assets/annotation-coin-icon.svg';
import SVGAnnotationCoinNoBorder from './assets/annotation-coin-icon-no-border.svg';
import SVGGreenAvatarBorder from './assets/green-avatar-border.svg';
import SVGRedAvatarBorder from './assets/red-avatar-border.svg';
import SVGLoadingItem from './assets/loading-item.svg';
import SVGMoneyHoarderBadge from './assets/money-hoarder-badge.svg';
import SVGImageIcon from './assets/images-icon.svg';
import SVGTimeIcon from './assets/time-icon.svg';
import SVGImageFinished from './assets/image-finished-icon.svg';

import SVGEnergizerIcon from './assets/energizer-button-icon.svg';
import SVGEnergizerIcon1 from './assets/gamification/energizer/Energizer-1.svg';
import SVGEnergizerIcon2 from './assets/gamification/energizer/Energizer-2.svg';
import SVGEnergizerIcon3 from './assets/gamification/energizer/Energizer-3.svg';
import SVGEnergizerIcon4 from './assets/gamification/energizer/Energizer-4.svg';
import SVGEnergizerIcon5 from './assets/gamification/energizer/Energizer-5.svg';
import SVGEnergizerIcon6 from './assets/gamification/energizer/Energizer-6.svg';
import SVGEnergizerIcon7 from './assets/gamification/energizer/Energizer-7.svg';
import SVGEnergizerIcon8 from './assets/gamification/energizer/Energizer-8.svg';
import SVGEnergizerIcon9 from './assets/gamification/energizer/Energizer-9.svg';
import SVGEnergizerIcon10 from './assets/gamification/energizer/Energizer-10.svg';
import SVGEnergizerIcon11 from './assets/gamification/energizer/Energizer-11.svg';

// Badges
import SVGBadgeGold from './assets/gamification/badges/badge-gold.svg';
import SVGBadgeSilver from './assets/gamification/badges/badge-silver.svg';
import SVGBadgeBronze from './assets/gamification/badges/badge-bronze.svg';
import SVGBadgeTest from './assets/gamification/badges/badge-test.svg';

import SVGBadgeAnnotatorGrey from './assets/gamification/badges/GreyV-1.svg';
import SVGBadgeAnnotatorBronze from './assets/gamification/badges/BronzeV-1.svg';
import SVGBadgeAnnotatorSilver from './assets/gamification/badges/SilverV-1.svg';
import SVGBadgeAnnotatorGold from './assets/gamification/badges/GoldV-1.svg';
import SVGBadgeAnnotationMachineGrey from './assets/gamification/badges/GreyV-2.svg';
import SVGBadgeAnnotationMachineBronze from './assets/gamification/badges/BronzeV-2.svg';
import SVGBadgeAnnotationMachineSilver from './assets/gamification/badges/SilverV-2.svg';
import SVGBadgeAnnotationMachineGold from './assets/gamification/badges/GoldV-2.svg';
import SVGBadgeTaggerGrey from './assets/gamification/badges/GreyV-3.svg';
import SVGBadgeTaggerBronze from './assets/gamification/badges/BronzeV-3.svg';
import SVGBadgeTaggerSilver from './assets/gamification/badges/SilverV-3.svg';
import SVGBadgeTaggerGold from './assets/gamification/badges/GoldV-3.svg';
import SVGBadgeTimeFliesGrey from './assets/gamification/badges/GreyV-4.svg';
import SVGBadgeTimeFliesBronze from './assets/gamification/badges/BronzeV-4.svg';
import SVGBadgeTimeFliesSilver from './assets/gamification/badges/SilverV-4.svg';
import SVGBadgeTimeFliesGold from './assets/gamification/badges/GoldV-4.svg';
import SVGBadgeSerialAnnotatorGrey from './assets/gamification/badges/GreyV-5.svg';
import SVGBadgeSerialAnnotatorBronze from './assets/gamification/badges/BronzeV-5.svg';
import SVGBadgeSerialAnnotatorSilver from './assets/gamification/badges/SilverV-5.svg';
import SVGBadgeSerialAnnotatorGold from './assets/gamification/badges/GoldV-5.svg';
import SVGBadgeEnergizedGrey from './assets/gamification/badges/GreyV-6.svg';
import SVGBadgeEnergizedBronze from './assets/gamification/badges/BronzeV-6.svg';
import SVGBadgeEnergizedSilver from './assets/gamification/badges/SilverV-6.svg';
import SVGBadgeEnergizedGold from './assets/gamification/badges/GoldV-6.svg';
import SVGBadgeEnergyCollectorGrey from './assets/gamification/badges/GreyV-7.svg';
import SVGBadgeEnergyCollectorBronze from './assets/gamification/badges/BronzeV-7.svg';
import SVGBadgeEnergyCollectorSilver from './assets/gamification/badges/SilverV-7.svg';
import SVGBadgeEnergyCollectorGold from './assets/gamification/badges/GoldV-7.svg';
import SVGBadgeBalancedEnergyGrey from './assets/gamification/badges/GreyV-8.svg';
import SVGBadgeBalancedEnergyBronze from './assets/gamification/badges/BronzeV-8.svg';
import SVGBadgeBalancedEnergySilver from './assets/gamification/badges/SilverV-8.svg';
import SVGBadgeBalancedEnergyGold from './assets/gamification/badges/GoldV-8.svg';
import SVGBadgeChallengerGrey from './assets/gamification/badges/GreyV-9.svg';
import SVGBadgeChallengerBronze from './assets/gamification/badges/BronzeV-9.svg';
import SVGBadgeChallengerSilver from './assets/gamification/badges/SilverV-9.svg';
import SVGBadgeChallengerGold from './assets/gamification/badges/GoldV-9.svg';
import SVGBadgeMillionaireGrey from './assets/gamification/badges/GreyV-10.svg';
import SVGBadgeMillionaireBronze from './assets/gamification/badges/BronzeV-10.svg';
import SVGBadgeMillionaireSilver from './assets/gamification/badges/SilverV-10.svg';
import SVGBadgeMillionaireGold from './assets/gamification/badges/GoldV-10.svg';
import SVGBadgeHoarderGrey from './assets/gamification/badges/GreyV-11.svg';
import SVGBadgeHoarderBronze from './assets/gamification/badges/BronzeV-11.svg';
import SVGBadgeHoarderSilver from './assets/gamification/badges/SilverV-11.svg';
import SVGBadgeHoarderGold from './assets/gamification/badges/GoldV-11.svg';
import SVGBadgeMoneyManGrey from './assets/gamification/badges/GreyV-12.svg';
import SVGBadgeMoneyManBronze from './assets/gamification/badges/BronzeV-12.svg';
import SVGBadgeMoneyManSilver from './assets/gamification/badges/SilverV-12.svg';
import SVGBadgeMoneyManGold from './assets/gamification/badges/GoldV-12.svg';
import SVGBadgeUnlockerGrey from './assets/gamification/badges/GreyV-13.svg';
import SVGBadgeUnlockerBronze from './assets/gamification/badges/BronzeV-13.svg';
import SVGBadgeUnlockerSilver from './assets/gamification/badges/SilverV-13.svg';
import SVGBadgeUnlockerGold from './assets/gamification/badges/GoldV-13.svg';
import SVGMysteryGiftGrey from './assets/gamification/badges/GreyV-14.svg';
import SVGMysteryGiftBronze from './assets/gamification/badges/BronzeV-14.svg';
import SVGMysteryGiftSilver from './assets/gamification/badges/SilverV-14.svg';
import SVGMysteryGiftGold from './assets/gamification/badges/GoldV-14.svg';
// hidden badges
import SVGFunHaterGrey from './assets/gamification/badges/GreyH-1.svg';
import SVGFunHaterGold from './assets/gamification/badges/GoldH-1.svg';
import SVGNightOwlGrey from './assets/gamification/badges/GreyH-2.svg';
import SVGNightOwlGold from './assets/gamification/badges/GoldH-2.svg';
import SVGChatMenaceGrey from './assets/gamification/badges/GreyH-3.svg';
import SVGChatMenaceGold from './assets/gamification/badges/GoldH-3.svg';
import SVGEforEffortGrey from './assets/gamification/badges/GreyH-4.svg';
import SVGEforEffortGold from './assets/gamification/badges/GoldH-4.svg';
import SVGCobraGrey from './assets/gamification/badges/GreyH-5.svg';
import SVGCobraGold from './assets/gamification/badges/GoldH-5.svg';
import SVGTetrisGrey from './assets/gamification/badges/GreyH-6.svg';
import SVGTetrisGold from './assets/gamification/badges/GoldH-6.svg';

// Statistic Icons
import SVGStatImagesAnnotated from './assets/gamification/statistics/S-1.svg';
import SVGStatTagsSet from './assets/gamification/statistics/S-2.svg';
import SVGStatAvgTime from './assets/gamification/statistics/S-3.svg';
import SVGStatAnnotationStreak from './assets/gamification/statistics/S-4.svg';
import SVGStatAnnotationTime from './assets/gamification/statistics/S-5.svg';
import SVGStatEnergyGained from './assets/gamification/statistics/S-6.svg';
import SVGStatTetris from './assets/gamification/statistics/S-7.svg';
import SVGStatQuiz from './assets/gamification/statistics/S-8.svg';
import SVGStatSnake from './assets/gamification/statistics/S-9.svg';
import SVGStatChallenges from './assets/gamification/statistics/S-10.svg';
import SVGStatItemsBought from './assets/gamification/statistics/S-11.svg';
import SVGStatAnnotationCoins from './assets/gamification/statistics/S-12.svg';
import SVGStatAnnotationCoinMax from './assets/gamification/statistics/S-13.svg';
import SVGStatBadges from './assets/gamification/statistics/S-14.svg';

// Shop Icons
import SVGAddChallenge from './assets/gamification/shop/add-challenge-icon.svg';
import SVGMysteryGift from './assets/gamification/shop/mystery-gift-icon.svg';
import SVGStreakSaver from './assets/gamification/shop/streak-saver-icon.svg';
import SVGShopButton from './assets/gamification/shop/shop-icon.svg';

export const CVATLogo = React.memo((): JSX.Element => <SVGCVATLogo />);
export const EmptyTasksIcon = React.memo((): JSX.Element => <SVGEmptyTasksIcon />);
export const CursorIcon = React.memo((): JSX.Element => <SVGCursorIcon />);
export const MoveIcon = React.memo((): JSX.Element => <SVGMoveIcon />);
export const RotateIcon = React.memo((): JSX.Element => <SVGRotateIcon />);
export const FitIcon = React.memo((): JSX.Element => <SVGFitIcon />);
export const ZoomIcon = React.memo((): JSX.Element => <SVGZoomIcon />);
export const RectangleIcon = React.memo((): JSX.Element => <SVGRectangleIcon />);
export const PolygonIcon = React.memo((): JSX.Element => <SVGPolygonIcon />);
export const PointIcon = React.memo((): JSX.Element => <SVGPointIcon />);
export const EllipseIcon = React.memo((): JSX.Element => <SVGEllipseIcon />);
export const PolylineIcon = React.memo((): JSX.Element => <SVGPolylineIcon />);
export const TagIcon = React.memo((): JSX.Element => <SVGTagIcon />);
export const MergeIcon = React.memo((): JSX.Element => <SVGMergeIcon />);
export const GroupIcon = React.memo((): JSX.Element => <SVGGroupIcon />);
export const SplitIcon = React.memo((): JSX.Element => <SVGSplitIcon />);
export const MainMenuIcon = React.memo((): JSX.Element => <SVGMainMenuIcon />);
export const SaveIcon = React.memo((): JSX.Element => <SVGSaveIcon />);
export const UndoIcon = React.memo((): JSX.Element => <SVGUndoIcon />);
export const RedoIcon = React.memo((): JSX.Element => <SVGRedoIcon />);
export const FirstIcon = React.memo((): JSX.Element => <SVGFirstIcon />);
export const BackJumpIcon = React.memo((): JSX.Element => <SVGBackJumpIcon />);
export const PreviousIcon = React.memo((): JSX.Element => <SVGPreviousIcon />);
export const PreviousFilteredIcon = React.memo((): JSX.Element => <SVGPreviousFilteredIcon />);
export const PreviousEmptyIcon = React.memo((): JSX.Element => <SVGPreviousEmptyIcon />);
export const PauseIcon = React.memo((): JSX.Element => <SVGPauseIcon />);
export const PlayIcon = React.memo((): JSX.Element => <SVGPlayIcon />);
export const NextIcon = React.memo((): JSX.Element => <SVGNextIcon />);
export const NextFilteredIcon = React.memo((): JSX.Element => <SVGNextFilteredIcon />);
export const NextEmptyIcon = React.memo((): JSX.Element => <SVGNextEmptyIcon />);
export const ForwardJumpIcon = React.memo((): JSX.Element => <SVGForwardJumpIcon />);
export const LastIcon = React.memo((): JSX.Element => <SVGLastIcon />);
export const InfoIcon = React.memo((): JSX.Element => <SVGInfoIcon />);
export const FullscreenIcon = React.memo((): JSX.Element => <SVGFullscreenIcon />);
export const ObjectOutsideIcon = React.memo((): JSX.Element => <SVGObjectOutsideIcon />);
export const BackgroundIcon = React.memo((): JSX.Element => <SVGBackgroundIcon />);
export const ForegroundIcon = React.memo((): JSX.Element => <SVGForegroundIcon />);
export const CubeIcon = React.memo((): JSX.Element => <SVGCubeIcon />);
export const ResetPerspectiveIcon = React.memo((): JSX.Element => <SVGResetPerspectiveIcon />);
export const AIToolsIcon = React.memo((): JSX.Element => <SVGAITools />);
export const ColorizeIcon = React.memo((): JSX.Element => <SVGColorizeIcon />);
export const BrainIcon = React.memo((): JSX.Element => <SVGBrain />);
export const OpenCVIcon = React.memo((): JSX.Element => <SVGOpenCV />);
export const FilterIcon = React.memo((): JSX.Element => <SVGFilterIcon />);
export const AzureProvider = React.memo((): JSX.Element => <SVGCVATAzureProvider />);
export const S3Provider = React.memo((): JSX.Element => <SVGCVATS3Provider />);
export const GoogleCloudProvider = React.memo((): JSX.Element => <SVGCVATGoogleCloudProvider />);
export const OpenVINOIcon = React.memo((): JSX.Element => <SVGOpenVINO />);
// gamification stuff

export const EnergizerIcon = React.memo((): JSX.Element => <SVGEnergizerIcon />);
export const EnergizerIcon1 = React.memo((): JSX.Element => <SVGEnergizerIcon1 />);
export const EnergizerIcon2 = React.memo((): JSX.Element => <SVGEnergizerIcon2 />);
export const EnergizerIcon3 = React.memo((): JSX.Element => <SVGEnergizerIcon3 />);
export const EnergizerIcon4 = React.memo((): JSX.Element => <SVGEnergizerIcon4 />);
export const EnergizerIcon5 = React.memo((): JSX.Element => <SVGEnergizerIcon5 />);
export const EnergizerIcon6 = React.memo((): JSX.Element => <SVGEnergizerIcon6 />);
export const EnergizerIcon7 = React.memo((): JSX.Element => <SVGEnergizerIcon7 />);
export const EnergizerIcon8 = React.memo((): JSX.Element => <SVGEnergizerIcon8 />);
export const EnergizerIcon9 = React.memo((): JSX.Element => <SVGEnergizerIcon9 />);
export const EnergizerIcon10 = React.memo((): JSX.Element => <SVGEnergizerIcon10 />);
export const EnergizerIcon11 = React.memo((): JSX.Element => <SVGEnergizerIcon11 />);
export const ImageFinishedIcon = React.memo((): JSX.Element => <SVGImageFinished />);

// Badges
export const BadgeIcon = React.memo((): JSX.Element => <SVGBadge />);
export const BadgeGreyIcon = React.memo((): JSX.Element => <SVGBadgeGrey />);
export const BadgeTooltipTest = React.memo((): JSX.Element => <Icon component={SVGBadgeGrey} />);
export const BadgeGoldIcon = React.memo((): JSX.Element => <SVGBadgeGold />);
export const BadgeSilverIcon = React.memo((): JSX.Element => <SVGBadgeSilver />);
export const BadgeBronzeIcon = React.memo((): JSX.Element => <SVGBadgeBronze />);
export const BadgeTestIcon = React.memo((): JSX.Element => <SVGBadgeTest />);

export const AnnotatorGrey = React.memo((): JSX.Element => <SVGBadgeAnnotatorGrey />);
export const AnnotatorBronze = React.memo((): JSX.Element => <SVGBadgeAnnotatorBronze />);
export const AnnotatorSilver = React.memo((): JSX.Element => <SVGBadgeAnnotatorSilver />);
export const AnnotatorGold = React.memo((): JSX.Element => <SVGBadgeAnnotatorGold />);
export const AnnotationMachineGrey = React.memo((): JSX.Element => <SVGBadgeAnnotationMachineGrey />);
export const AnnotationMachineBronze = React.memo((): JSX.Element => <SVGBadgeAnnotationMachineBronze />);
export const AnnotationMachineSilver = React.memo((): JSX.Element => <SVGBadgeAnnotationMachineSilver />);
export const AnnotationMachineGold = React.memo((): JSX.Element => <SVGBadgeAnnotationMachineGold />);
export const TaggerGrey = React.memo((): JSX.Element => <SVGBadgeTaggerGrey />);
export const TaggerBronze = React.memo((): JSX.Element => <SVGBadgeTaggerBronze />);
export const TaggerSilver = React.memo((): JSX.Element => <SVGBadgeTaggerSilver />);
export const TaggerGold = React.memo((): JSX.Element => <SVGBadgeTaggerGold />);
export const TimeFliesGrey = React.memo((): JSX.Element => <SVGBadgeTimeFliesGrey />);
export const TimeFliesBronze = React.memo((): JSX.Element => <SVGBadgeTimeFliesBronze />);
export const TimeFliesSilver = React.memo((): JSX.Element => <SVGBadgeTimeFliesSilver />);
export const TimeFliesGold = React.memo((): JSX.Element => <SVGBadgeTimeFliesGold />);
export const SerialAnnotatorGrey = React.memo((): JSX.Element => <SVGBadgeSerialAnnotatorGrey />);
export const SerialAnnotatorBronze = React.memo((): JSX.Element => <SVGBadgeSerialAnnotatorBronze />);
export const SerialAnnotatorSilver = React.memo((): JSX.Element => <SVGBadgeSerialAnnotatorSilver />);
export const SerialAnnotatorGold = React.memo((): JSX.Element => <SVGBadgeSerialAnnotatorGold />);
export const EnergizedGrey = React.memo((): JSX.Element => <SVGBadgeEnergizedGrey />);
export const EnergizedBronze = React.memo((): JSX.Element => <SVGBadgeEnergizedBronze />);
export const EnergizedSilver = React.memo((): JSX.Element => <SVGBadgeEnergizedSilver />);
export const EnergizedGold = React.memo((): JSX.Element => <SVGBadgeEnergizedGold />);
export const EnergyCollectorGrey = React.memo((): JSX.Element => <SVGBadgeEnergyCollectorGrey />);
export const EnergyCollectorBronze = React.memo((): JSX.Element => <SVGBadgeEnergyCollectorBronze />);
export const EnergyCollectorSilver = React.memo((): JSX.Element => <SVGBadgeEnergyCollectorSilver />);
export const EnergyCollectorGold = React.memo((): JSX.Element => <SVGBadgeEnergyCollectorGold />);
export const BalancedEnergyGrey = React.memo((): JSX.Element => <SVGBadgeBalancedEnergyGrey />);
export const BalancedEnergyBronze = React.memo((): JSX.Element => <SVGBadgeBalancedEnergyBronze />);
export const BalancedEnergySilver = React.memo((): JSX.Element => <SVGBadgeBalancedEnergySilver />);
export const BalancedEnergyGold = React.memo((): JSX.Element => <SVGBadgeBalancedEnergyGold />);
export const ChallengerGrey = React.memo((): JSX.Element => <SVGBadgeChallengerGrey />);
export const ChallengerBronze = React.memo((): JSX.Element => <SVGBadgeChallengerBronze />);
export const ChallengerSilver = React.memo((): JSX.Element => <SVGBadgeChallengerSilver />);
export const ChallengerGold = React.memo((): JSX.Element => <SVGBadgeChallengerGold />);
export const MillionaireGrey = React.memo((): JSX.Element => <SVGBadgeMillionaireGrey />);
export const MillionaireBronze = React.memo((): JSX.Element => <SVGBadgeMillionaireBronze />);
export const MillionaireSilver = React.memo((): JSX.Element => <SVGBadgeMillionaireSilver />);
export const MillionaireGold = React.memo((): JSX.Element => <SVGBadgeMillionaireGold />);
export const HoarderGrey = React.memo((): JSX.Element => <SVGBadgeHoarderGrey />);
export const HoarderBronze = React.memo((): JSX.Element => <SVGBadgeHoarderBronze />);
export const HoarderSilver = React.memo((): JSX.Element => <SVGBadgeHoarderSilver />);
export const HoarderGold = React.memo((): JSX.Element => <SVGBadgeHoarderGold />);
export const MoneyManGrey = React.memo((): JSX.Element => <SVGBadgeMoneyManGrey />);
export const MoneyManBronze = React.memo((): JSX.Element => <SVGBadgeMoneyManBronze />);
export const MoneyManSilver = React.memo((): JSX.Element => <SVGBadgeMoneyManSilver />);
export const MoneyManGold = React.memo((): JSX.Element => <SVGBadgeMoneyManGold />);
export const UnlockerGrey = React.memo((): JSX.Element => <SVGBadgeUnlockerGrey />);
export const UnlockerBronze = React.memo((): JSX.Element => <SVGBadgeUnlockerBronze />);
export const UnlockerSilver = React.memo((): JSX.Element => <SVGBadgeUnlockerSilver />);
export const UnlockerGold = React.memo((): JSX.Element => <SVGBadgeUnlockerGold />);
export const MysteryGiftBadgeGrey = React.memo((): JSX.Element => <SVGMysteryGiftGrey />);
export const MysteryGiftBadgeBronze = React.memo((): JSX.Element => <SVGMysteryGiftBronze />);
export const MysteryGiftBadgeSilver = React.memo((): JSX.Element => <SVGMysteryGiftSilver />);
export const MysteryGiftBadgeGold = React.memo((): JSX.Element => <SVGMysteryGiftGold />);
// hidden badges
export const FunHaterGrey = React.memo((): JSX.Element => <SVGFunHaterGrey />);
export const FunHaterGold = React.memo((): JSX.Element => <SVGFunHaterGold />);
export const NightOwlGrey = React.memo((): JSX.Element => <SVGNightOwlGrey />);
export const NightOwlGold = React.memo((): JSX.Element => <SVGNightOwlGold />);
export const ChatMenaceGrey = React.memo((): JSX.Element => <SVGChatMenaceGrey />);
export const ChatMenaceGold = React.memo((): JSX.Element => <SVGChatMenaceGold />);
export const EforEffortGrey = React.memo((): JSX.Element => <SVGEforEffortGrey />);
export const EforEffortGold = React.memo((): JSX.Element => <SVGEforEffortGold />);
export const CobraGrey = React.memo((): JSX.Element => <SVGCobraGrey />);
export const CobraGold = React.memo((): JSX.Element => <SVGCobraGold />);
export const TetrisGrey = React.memo((): JSX.Element => <SVGTetrisGrey />);
export const TetrisGold = React.memo((): JSX.Element => <SVGTetrisGold />);

// Statistics
export const ImagesAnnotatedIcon = React.memo((): JSX.Element => <SVGStatImagesAnnotated />);
export const TagsSetIcon = React.memo((): JSX.Element => <SVGStatTagsSet />);
export const AvgTimeIcon = React.memo((): JSX.Element => <SVGStatAvgTime />);
export const AnnotationStreakIcon = React.memo((): JSX.Element => <SVGStatAnnotationStreak />);
export const AnnotationTimeIcon = React.memo((): JSX.Element => <SVGStatAnnotationTime />);
export const EnergyGainedIcon = React.memo((): JSX.Element => <SVGStatEnergyGained />);
export const TetrisIcon = React.memo((): JSX.Element => <SVGStatTetris />);
export const QuizIcon = React.memo((): JSX.Element => <SVGStatQuiz />);
export const SnakeIcon = React.memo((): JSX.Element => <SVGStatSnake />);
export const ChallengesIcon = React.memo((): JSX.Element => <SVGStatChallenges />);
export const ItemsBoughtIcon = React.memo((): JSX.Element => <SVGStatItemsBought />);
export const AnnotationCoinsObtainedIcon = React.memo((): JSX.Element => <SVGStatAnnotationCoins />);
export const AnnotationCoinsMaxIcon = React.memo((): JSX.Element => <SVGStatAnnotationCoinMax />);
export const BadgesObtainedIcon = React.memo((): JSX.Element => <SVGStatBadges />);

export const AnnotationCoinIcon = React.memo((): JSX.Element => <SVGAnnotationCoin />);
export const AnnotationCoinNoBorderIcon = React.memo((): JSX.Element => <SVGAnnotationCoinNoBorder />);
export const GreenAvatarBorderIcon = React.memo((): JSX.Element => <SVGGreenAvatarBorder />);
export const RedAvatarBorderIcon = React.memo((): JSX.Element => <SVGRedAvatarBorder />);
export const LoadingItemIcon = React.memo((): JSX.Element => <SVGLoadingItem />);
export const MoneyHoarderBadgeIcon = React.memo((): JSX.Element => <SVGMoneyHoarderBadge />);
export const ImageIcon = React.memo((): JSX.Element => <SVGImageIcon />);
export const TimeIcon = React.memo((): JSX.Element => <SVGTimeIcon />);

// Shop
export const AddChallengeIcon = React.memo((): JSX.Element => <SVGAddChallenge />);
export const MysteryGiftIcon = React.memo((): JSX.Element => <SVGMysteryGift />);
export const StreakSaverIcon = React.memo((): JSX.Element => <SVGStreakSaver />);
export const ShopIcon = React.memo((): JSX.Element => <SVGShopButton />);
